### ISSUE TITLE
Are workspace translations planned ?

### ISSUE THREAD

**Issue by eldk** [Vizzuality/GlobalFishingWatch#475]
Hello,

Are there some plan to translate workspace ?

https://github.com/Vizzuality/GlobalFishingWatch/blob/mapster/public/workspace.json

Thanks,

Eric

**Comment by pwoods25443** [comment]
@eldk you mean i18n for the workspace content?  If so, how do you think we should handle it?

**Comment by eldk** [comment]
Hello,

Sorry for the late answer.

>you mean i18n for the workspace content ?

Yes

>If so, how do you think we should handle it

Some clues on StackOverflow and open community tools for internatiolization in javascript : http://stackoverflow.com/questions/3084675/how-does-internationalization-work-in-javascript

Thanks,

Eric

**Comment by tiagojsag** [comment]
@eldk thanks for your feedback

From your reply, I assume you are looking for information on support for multiple languages in the Global Fishing Watch map and pages.

The file you pointed to handles the configuration of the map, for things such as which layers are listed and such. While it does have some literals in English, it is not meant to be a comprehensive list of all literals on the page that would need to be translated in order to add multilanguage support to Global Fishing Watch.

If you want to suggest adding translation to the site or map, or ask for other features, please get in touch with us using the contact form at http://globalfishingwatch.org/contact-us 

Thanks once again
