### ISSUE TITLE
Subscriptions: Review endpoint for report subscriptions

### ISSUE THREAD

**Issue by nerik** [Vizzuality/GlobalFishingWatch#816]
(From Andres)

I've just pushed a new API version to your environment which contains a new endpoint for report subscriptions. It's a mock service, the subscription itself is not implemented, but the API inputs and output won't change. Please take a look at the documentation at http://globalfishingwatch.io/api-docs/console/?url=https://api-dot-world-fishing-827.appspot.com/api/v2#!/Tile_services/post_v2_tilesets_tileset_reports_subscriptions and tell me what you think

**Comment by nerik** [comment]
I have two questions:

1. Currently, even if it's not documented in the Swagger file, the report API supports filtering by flags (a `flags` array with ISO2 codes strings). We know have arbitrary filters instead of just flags, should we:
a. Expand filtering to arbitrary filters? ie replace `flags: ['ES']` with `filters: [{id: 'indo_registered_gear_type', values: ['ES']` or `filters: [{id: 'flag', values: [1,5,14]` 
b. Keep the flags array only (this would still need a frontend fix on the filters feature)  
c. Remove the filtering capabilities
(in all cases that would need to be implemented for both reports and subscriptions endpoints)

2. What are the accepted values for `recurrency`? `daily`/`weekly`/`monthly` I presume?

**Comment by andres-arana** [comment]
@nerik:

1. The filters are documented in the swagger file, but not on the example value. As a general guideline, example values just provide a minimum value which allows you to call the API, and in this case the flag filters are optional. Click on the "Model' link on top of the report parameter and you'll see the whole documentation of the value. Regarding the arbitrary filters schema, I prefer having explicit fields for the filters we actually support. Having a generic interface doesn't really do much, since we have to explicitly implement the filters anyways and we also need to validate that the filter types correspond to one of the supported types.

2. Again, check the value documentation. The accepted values are `daily`, `weekly` and `monthly`.

**Comment by nerik** [comment]
Okay, thanks.
